name: online_course
description: Online Course App.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.19.3
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_custom_tab_bar: ^1.2.1
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.7
  get_it: ^7.6.4
  http: ^1.1.0
  mocktail: ^1.0.0
  readmore: ^2.2.0
  media_kit: ^1.1.10                             # Primary package.
  media_kit_video: ^1.2.4                        # For video rendering.
  media_kit_libs_video: ^1.0.4   
  razorpay_web: ^1.3.3
  bottom_sheet: ^4.0.4
  rive: ^0.13.2
  url_launcher: ^6.2.6
  flutter_firebase_chat_core: ^1.6.7
  syncfusion_flutter_pdfviewer: ^24.2.8
  google_sign_in: ^6.2.1
  bubble: ^1.2.1
  
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/categories/
    - assets/anim/succes.riv
